name: unit
description: "Three types: Angle, HourAngle, and Time, useful in astronomy applications."
version: 1.0.3
homepage: https://github.com/shawnlauzon/unit

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.20.1
